[pytest]
pythonpath = .
addopts = --alluredir=allure-results -v -s --base-url=https://restful-booker.herokuapp.com
# Test files and functions locations
testpaths = tests
python_files = test_*.py
python_functions = test_*

markers =
    skip_cleanup: skip the DELETE step for unique_booking fixture